#application
spring.application.name=SmartTaskFlow
server.port=8080

#DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username={}
spring.datasource.password={}
spring.datasource.url=jdbc:postgresql://localhost:5432/SmartTaskFlow

#nibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#jwt
jwt.secret={}
jwt.expiration=900000

#logging
logging.level.root=INFO
logging.file.name={}

# what kind of metrics, statistics and info from spring boot actuator would be available for access from HTTP
management.endpoints.web.exposure.include=health,info,prometheus

# turn on ability to provide metrics at Prometheus format on '/actuator/prometheus' endpoint
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator

